# Generated by Django 3.2.5 on 2022-01-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cUsers', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employer'), (2, 'Employee'), (3, 'secretary'), (4, 'supervisor')], null=True),
        ),
    ]
